### PR TITLE
Preliminary fixes for dark mode rendering

### PR DESCRIPTION
**Pull request by j6k4m8**
- [x] themes for the editor
- [x] styling for the page
- [x] readability / contrast checks for text color

image

image

### CODE REVIEW

**Comment by dxenes1** [comment]
Hmm getting this error when trying to build the motifstudio dockerfile!
```
------
 > [build 6/6] RUN npm run build:
0.160 
0.160 > motifstudio-web@0.1.0 build
0.160 > next build
0.160 
0.455 Attention: Next.js now collects completely anonymous telemetry regarding usage.
0.455 This information is used to shape Next.js' roadmap and prioritize features.
0.455 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
0.455 https://nextjs.org/telemetry
0.455 
0.489   ▲ Next.js 14.2.5
0.489 
0.526    Creating an optimized production build ...
1.837  ⚠ For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
1.837 Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
5.774  ⚠ For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
5.774 Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
8.279  ✓ Compiled successfully
8.280    Skipping validation of types
8.280    Skipping linting
8.436    Collecting page data ...
8.887    Generating static pages (0/5) ...
9.025    Generating static pages (1/5) 
9.025    Generating static pages (2/5) 
9.025    Generating static pages (3/5) 
9.047 ReferenceError: window is not defined
9.047     at /app/.next/server/app/page.js:22:8976
9.047     at rt (/app/.next/server/app/page.js:22:9155)
9.047     at nj (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
9.047     at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
9.047     at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
9.047     at nI (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47010)
9.047     at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47717)
9.047     at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
9.047     at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
9.047     at nB (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538) {
9.047   digest: '3042917380'
9.047 }
9.047 
9.047 Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
9.047 
9.047 ReferenceError: window is not defined
9.047     at /app/.next/server/app/page.js:22:8976
9.047     at rt (/app/.next/server/app/page.js:22:9155)
9.047     at nj (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
9.047     at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
9.047     at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
9.047     at nI (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47010)
9.047     at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47717)
9.047     at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
9.047     at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
9.047     at nB (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
9.049  ✓ Generating static pages (5/5)
9.052 
9.052 > Export encountered errors on following paths:
9.052   /page: /
------
Dockerfile:21
--------------------
  19 |     
  20 |     # Build app to build/ folder
  21 | >>> RUN npm run build
  22 |     
  23 |     # Static serving environment
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
```

**Comment by j6k4m8** [comment]
weird, me too....

**Comment by j6k4m8** [comment]
ahh, okay. I think this is from the new URL feature (#36) and unrelated to the dark mode PR. But I don't know how I didn't notice this (nice catch! glad you CR'd!).

I think it's trying to do SSR with the nextjs build but `window` doesn't exist server-side... let me brainstorm how to fix that...

**Comment by dxenes1** [comment]
Sounds good, also happening to me when I try to run it locally with node v18.0

**Review by dxenes1 — APPROVED** [review]
tested and LGTM!

**Pull request merged**
